# Generated by Django 4.2.7 on 2025-12-19 18:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("admin", "Administrator"),
                            ("support", "Support Staff"),
                            ("moderator", "Moderator"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_seller_approved", models.BooleanField(default=False)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("two_factor_secret", models.CharField(blank=True, max_length=32)),
                ("pgp_public_key", models.TextField(blank=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_sales", models.PositiveIntegerField(default=0)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "escrow_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users_custom_user",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_order_updates", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("email_promotions", models.BooleanField(default=False)),
                ("email_security_alerts", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=False)),
                ("site_order_updates", models.BooleanField(default=True)),
                ("site_messages", models.BooleanField(default=True)),
                ("site_promotions", models.BooleanField(default=True)),
                ("email_new_orders", models.BooleanField(default=True)),
                ("email_reviews", models.BooleanField(default=True)),
                ("email_low_stock", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification settings",
                "verbose_name_plural": "notification settings",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("client", "Client"),
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("moderator", "Moderator"),
                            ("support", "Support Staff"),
                            ("account_manager", "Account Manager"),
                            ("compliance", "Compliance Officer"),
                            ("military_auditor", "Military Auditor"),
                            ("system_admin", "System Administrator"),
                            ("super_admin", "Super Administrator"),
                            ("api_user", "API User"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("can_view_products", models.BooleanField(default=True)),
                ("can_purchase", models.BooleanField(default=False)),
                ("can_sell", models.BooleanField(default=False)),
                ("can_moderate", models.BooleanField(default=False)),
                ("can_audit", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_access_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False, help_text="System roles cannot be deleted"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher priority roles override lower ones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "db_table": "users_role",
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="users_role_code_7e9d84_idx"),
                    models.Index(
                        fields=["is_active"], name="users_role_is_acti_ed939d_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="role_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Detailed role with permissions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.role",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_user_session",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_activity"],
                        name="users_user__user_id_0c2a29_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="users_user__session_c6bca5_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="users_user__ip_addr_00e19b_idx",
                    ),
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="users_user__is_acti_949926_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSecurityKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("fido2", "FIDO2/WebAuthn"),
                            ("totp", "TOTP (Time-based)"),
                            ("backup", "Backup Code"),
                            ("sms", "SMS Code"),
                            ("email", "Email Code"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for the key", max_length=100
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True, help_text="FIDO2 credential ID", max_length=500
                    ),
                ),
                ("public_key", models.TextField(blank=True)),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, help_text="Encrypted secret", max_length=500
                    ),
                ),
                (
                    "counter",
                    models.PositiveIntegerField(
                        default=0, help_text="FIDO2 signature counter"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "security key",
                "verbose_name_plural": "security keys",
                "db_table": "users_security_key",
                "ordering": ["-is_primary", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="users_secur_user_id_a1f27d_idx",
                    ),
                    models.Index(
                        fields=["key_type"], name="users_secur_key_typ_b94e3c_idx"
                    ),
                    models.Index(
                        fields=["credential_id"], name="users_secur_credent_dc561f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password Change"),
                            ("email_change", "Email Change"),
                            ("profile_update", "Profile Update"),
                            ("2fa_enable", "2FA Enabled"),
                            ("2fa_disable", "2FA Disabled"),
                            ("order_placed", "Order Placed"),
                            ("withdrawal", "Withdrawal Request"),
                            ("deposit", "Deposit"),
                            ("suspicious", "Suspicious Activity"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "activity log",
                "verbose_name_plural": "activity logs",
                "db_table": "users_user_activity_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_user__user_id_6cdf41_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="users_user__activit_d21d2e_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="users_user__ip_addr_9182cf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=50)),
                ("github_username", models.CharField(blank=True, max_length=50)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("preferred_language", models.CharField(default="en", max_length=10)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="dark",
                        max_length=20,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("last_profile_update", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "db_table": "users_profile",
                "indexes": [
                    models.Index(
                        fields=["user"], name="users_profi_user_id_783607_idx"
                    ),
                    models.Index(
                        fields=["company_name"], name="users_profi_company_ecb4ee_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_view_all_products", models.BooleanField(default=False)),
                ("can_view_restricted_products", models.BooleanField(default=False)),
                ("can_create_products", models.BooleanField(default=False)),
                ("can_edit_own_products", models.BooleanField(default=False)),
                ("can_edit_all_products", models.BooleanField(default=False)),
                ("can_delete_products", models.BooleanField(default=False)),
                ("can_view_own_orders", models.BooleanField(default=True)),
                ("can_view_all_orders", models.BooleanField(default=False)),
                ("can_create_orders", models.BooleanField(default=True)),
                ("can_cancel_orders", models.BooleanField(default=False)),
                ("can_approve_orders", models.BooleanField(default=False)),
                ("can_view_users", models.BooleanField(default=False)),
                ("can_edit_users", models.BooleanField(default=False)),
                ("can_delete_users", models.BooleanField(default=False)),
                ("can_verify_users", models.BooleanField(default=False)),
                ("can_submit_verification", models.BooleanField(default=True)),
                ("can_review_verification", models.BooleanField(default=False)),
                ("can_approve_verification", models.BooleanField(default=False)),
                ("can_create_tickets", models.BooleanField(default=True)),
                ("can_view_all_tickets", models.BooleanField(default=False)),
                ("can_resolve_tickets", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=False)),
                ("can_export_data", models.BooleanField(default=False)),
                ("can_manage_settings", models.BooleanField(default=False)),
                ("can_access_logs", models.BooleanField(default=False)),
                ("can_manage_roles", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "permission matrix",
                "verbose_name_plural": "permission matrices",
                "db_table": "users_permission_matrix",
                "indexes": [
                    models.Index(fields=["role"], name="users_permi_role_id_3d1b16_idx")
                ],
                "unique_together": {("role",)},
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_order_updates", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("email_promotions", models.BooleanField(default=False)),
                ("email_security_alerts", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=False)),
                ("email_verification_updates", models.BooleanField(default=True)),
                ("site_order_updates", models.BooleanField(default=True)),
                ("site_messages", models.BooleanField(default=True)),
                ("site_promotions", models.BooleanField(default=True)),
                ("site_verification_updates", models.BooleanField(default=True)),
                ("email_new_orders", models.BooleanField(default=True)),
                ("email_reviews", models.BooleanField(default=True)),
                ("email_low_stock", models.BooleanField(default=True)),
                ("email_disputes", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=False)),
                ("push_order_updates", models.BooleanField(default=True)),
                ("push_messages", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "db_table": "users_notification_preference",
                "indexes": [
                    models.Index(fields=["user"], name="users_notif_user_id_89ae99_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email used in login attempt", max_length=254
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Successful"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("locked", "Account Locked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("isp", models.CharField(blank=True, max_length=200)),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "risk_score",
                    models.PositiveIntegerField(
                        default=0, help_text="0-100 risk assessment"
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "login audit",
                "verbose_name_plural": "login audits",
                "db_table": "users_login_audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_login_user_id_3a29c7_idx",
                    ),
                    models.Index(
                        fields=["email", "-created_at"],
                        name="users_login_email_dbb4f3_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="users_login_ip_addr_3e3738_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="users_login_status_509292_idx",
                    ),
                    models.Index(
                        fields=["is_suspicious"], name="users_login_is_susp_ec5c6a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AddressBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping Address"),
                            ("billing", "Billing Address"),
                            ("both", "Shipping & Billing"),
                        ],
                        default="shipping",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("recipient_name", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=255)),
                ("street_address_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_book",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "address book entry",
                "verbose_name_plural": "address book entries",
                "db_table": "users_address_book",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "address_type"],
                        name="users_addre_user_id_adaa2e_idx",
                    ),
                    models.Index(
                        fields=["is_default"], name="users_addre_is_defa_cda90c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="users_custo_email_bcd0b7_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["username"], name="users_custo_usernam_e890ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role"], name="users_custo_role_08264f_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="users_custo_is_acti_ab471b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["-date_joined"], name="users_custo_date_jo_284f61_idx"
            ),
        ),
    ]
