# Generated by Django 4.2.7 on 2025-12-20 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
        ("verification", "0002_alter_verificationlog_action_type_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("product_added", "New Product Added"),
                            ("robot_added", "New Robot Added"),
                            ("verification_approved", "Verification Approved"),
                            ("verification_rejected", "Verification Rejected"),
                            ("verification_updated", "Verification Status Updated"),
                            ("purchase_request_approved", "Purchase Request Approved"),
                            ("purchase_request_rejected", "Purchase Request Rejected"),
                            ("order_status_changed", "Order Status Changed"),
                            ("message_received", "New Message Received"),
                            ("system_alert", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="verification.verificationrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "users_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="users_notif_user_id_f3f50a_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="users_notif_notific_589b34_idx",
                    ),
                ],
            },
        ),
    ]
