# Generated by Django 4.2.7 on 2025-12-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_password_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("product_added", "New Product Added"),
                    ("robot_added", "New Robot Added"),
                    ("verification_approved", "Verification Approved"),
                    ("verification_rejected", "Verification Rejected"),
                    ("verification_updated", "Verification Status Updated"),
                    ("license_approved", "Export License Approved"),
                    ("license_rejected", "Export License Rejected"),
                    ("license_info_required", "Additional Info Required"),
                    ("license_suspended", "Export License Suspended"),
                    ("license_expiring", "Export License Expiring Soon"),
                    ("purchase_request_approved", "Purchase Request Approved"),
                    ("purchase_request_rejected", "Purchase Request Rejected"),
                    ("order_status_changed", "Order Status Changed"),
                    ("message_received", "New Message Received"),
                    ("system_alert", "System Alert"),
                ],
                max_length=50,
            ),
        ),
    ]
