# Generated by Django 4.2.7 on 2025-12-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="detected_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="detected_country",
            field=models.CharField(
                blank=True, help_text="Auto-detected from IP", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="detected_country_code",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
