# Generated by Django 4.2.7 on 2025-12-19 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certification_type",
                    models.CharField(
                        choices=[
                            ("pilot_license", "Pilot License"),
                            ("drone_license", "Drone Operator License"),
                            ("security_clearance", "Security Clearance"),
                            ("export_license", "Export License"),
                            ("professional", "Professional Certification"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("certification_number", models.CharField(max_length=100)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="verification/certificates/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "certification",
                "verbose_name_plural": "certifications",
                "db_table": "verification_certification",
            },
        ),
        migrations.CreateModel(
            name="ClearanceLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("none", "No Clearance"),
                            ("public", "Public Trust"),
                            ("confidential", "Confidential"),
                            ("secret", "Secret"),
                            ("top_secret", "Top Secret"),
                            ("military", "Military Clearance"),
                            ("government", "Government Clearance"),
                            ("contractor", "Defense Contractor"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("can_access_restricted", models.BooleanField(default=False)),
                ("can_access_military", models.BooleanField(default=False)),
                ("can_access_export_controlled", models.BooleanField(default=False)),
                (
                    "minimum_clearance_required",
                    models.CharField(
                        choices=[
                            ("none", "No Clearance"),
                            ("public", "Public Trust"),
                            ("confidential", "Confidential"),
                            ("secret", "Secret"),
                            ("top_secret", "Top Secret"),
                            ("military", "Military Clearance"),
                            ("government", "Government Clearance"),
                            ("contractor", "Defense Contractor"),
                        ],
                        default="none",
                        help_text="Minimum clearance level required to access this level",
                        max_length=30,
                    ),
                ),
                (
                    "validity_months",
                    models.PositiveIntegerField(
                        default=12, help_text="Clearance validity period in months"
                    ),
                ),
                ("requires_renewal", models.BooleanField(default=True)),
                ("requires_background_check", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher priority = higher clearance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "clearance level",
                "verbose_name_plural": "clearance levels",
                "db_table": "verification_clearance_level",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for requesting verification"),
                ),
                (
                    "intended_use",
                    models.TextField(help_text="Intended use of restricted products"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_clearance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Currently assigned clearance level",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_clearances",
                        to="verification.clearancelevel",
                    ),
                ),
                (
                    "requested_clearance",
                    models.ForeignKey(
                        help_text="Requested clearance level",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_requests",
                        to="verification.clearancelevel",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "verification request",
                "verbose_name_plural": "verification requests",
                "db_table": "verification_verification_request",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("request_submitted", "Request Submitted"),
                            ("document_uploaded", "Document Uploaded"),
                            ("review_started", "Review Started"),
                            ("review_completed", "Review Completed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("clearance_assigned", "Clearance Assigned"),
                            ("clearance_revoked", "Clearance Revoked"),
                            ("expired", "Expired"),
                            ("renewed", "Renewed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_verification_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="verification.verificationrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "verification log",
                "verbose_name_plural": "verification logs",
                "db_table": "verification_verification_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MilitaryAffiliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("army", "Army"),
                            ("navy", "Navy"),
                            ("air_force", "Air Force"),
                            ("marines", "Marines"),
                            ("coast_guard", "Coast Guard"),
                            ("reserves", "Reserves"),
                            ("national_guard", "National Guard"),
                            ("veteran", "Veteran"),
                            ("civilian_contractor", "Civilian Contractor"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("enlisted", "Enlisted"),
                            ("officer", "Officer"),
                            ("warrant_officer", "Warrant Officer"),
                            ("civilian", "Civilian"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rank_title", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(blank=True, max_length=200)),
                ("service_number", models.CharField(blank=True, max_length=100)),
                ("is_active_duty", models.BooleanField(default=False)),
                ("is_veteran", models.BooleanField(default=False)),
                ("is_reservist", models.BooleanField(default=False)),
                ("is_contractor", models.BooleanField(default=False)),
                ("service_start_date", models.DateField(blank=True, null=True)),
                ("service_end_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="military_affiliation",
                        to="verification.verificationrequest",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_military_affiliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "military affiliation",
                "verbose_name_plural": "military affiliations",
                "db_table": "verification_military_affiliation",
            },
        ),
        migrations.CreateModel(
            name="IdentityDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("drivers_license", "Driver's License"),
                            ("national_id", "National ID"),
                            ("military_id", "Military ID"),
                            ("government_id", "Government ID"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("document_number", models.CharField(max_length=100)),
                ("issuing_country", models.CharField(max_length=100)),
                ("issuing_authority", models.CharField(blank=True, max_length=200)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "front_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="verification/documents/"
                    ),
                ),
                (
                    "back_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="verification/documents/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_documents",
                        to="verification.verificationrequest",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "identity document",
                "verbose_name_plural": "identity documents",
                "db_table": "verification_identity_document",
            },
        ),
        migrations.AddIndex(
            model_name="clearancelevel",
            index=models.Index(fields=["code"], name="verificatio_code_738a05_idx"),
        ),
        migrations.AddIndex(
            model_name="clearancelevel",
            index=models.Index(
                fields=["is_active", "priority"], name="verificatio_is_acti_22f698_idx"
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="verification_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="verification.verificationrequest",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_certifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["user", "status"], name="verificatio_user_id_fb6a25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["status", "-submitted_at"], name="verificatio_status_071019_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["requested_clearance"], name="verificatio_request_822b64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["current_clearance"], name="verificatio_current_73f908_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationlog",
            index=models.Index(
                fields=["verification_request", "-created_at"],
                name="verificatio_verific_a1dc46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationlog",
            index=models.Index(
                fields=["user", "-created_at"], name="verificatio_user_id_949819_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationlog",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="verificatio_action__a0dfbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="militaryaffiliation",
            index=models.Index(
                fields=["verification_request"], name="verificatio_verific_97efb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="militaryaffiliation",
            index=models.Index(
                fields=["branch", "is_verified"], name="verificatio_branch_a0c786_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identitydocument",
            index=models.Index(
                fields=["verification_request"], name="verificatio_verific_810531_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identitydocument",
            index=models.Index(
                fields=["is_verified"], name="verificatio_is_veri_746fbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["verification_request"], name="verificatio_verific_74fde0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["certification_type", "is_verified"],
                name="verificatio_certifi_b36699_idx",
            ),
        ),
    ]
