# Generated by Django 4.2.7 on 2025-12-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("request_submitted", "Request Submitted"),
                    ("document_uploaded", "Document Uploaded"),
                    ("review_started", "Review Started"),
                    ("review_completed", "Review Completed"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("withdrawn", "Withdrawn"),
                    ("clearance_assigned", "Clearance Assigned"),
                    ("clearance_revoked", "Clearance Revoked"),
                    ("expired", "Expired"),
                    ("renewed", "Renewed"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
