# Generated by Django 4.2.7 on 2025-12-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0002_alter_verificationlog_action_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="militaryaffiliation",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("army", "Army"),
                    ("navy", "Navy"),
                    ("air_force", "Air Force"),
                    ("marines", "Marines"),
                    ("coast_guard", "Coast Guard"),
                    ("reserves", "Reserves"),
                    ("national_guard", "National Guard"),
                    ("veteran", "Veteran"),
                    ("civilian_contractor", "Civilian Contractor"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
