# Generated by Django 4.2.7 on 2025-12-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0003_alter_militaryaffiliation_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clearancelevel",
            name="code",
            field=models.CharField(
                choices=[
                    ("none", "No Clearance"),
                    ("public", "Public Trust"),
                    ("age_restricted", "Age Restricted (18+)"),
                    ("confidential", "Confidential"),
                    ("secret", "Secret"),
                    ("top_secret", "Top Secret"),
                    ("military", "Military Clearance"),
                    ("government", "Government Clearance"),
                    ("contractor", "Defense Contractor"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="clearancelevel",
            name="minimum_clearance_required",
            field=models.CharField(
                choices=[
                    ("none", "No Clearance"),
                    ("public", "Public Trust"),
                    ("age_restricted", "Age Restricted (18+)"),
                    ("confidential", "Confidential"),
                    ("secret", "Secret"),
                    ("top_secret", "Top Secret"),
                    ("military", "Military Clearance"),
                    ("government", "Government Clearance"),
                    ("contractor", "Defense Contractor"),
                ],
                default="none",
                help_text="Minimum clearance level required to access this level",
                max_length=30,
            ),
        ),
    ]
