# Generated by Django 4.2.7 on 2025-12-21 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("verification", "0005_add_research_clearance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Export License"),
                            ("commercial", "Commercial Export License"),
                            ("government", "Government Export License"),
                            ("defense_contractor", "Defense Contractor License"),
                            ("research", "Research & Development License"),
                            ("reseller", "Authorized Reseller License"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated upon approval",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Required for commercial/government licenses",
                        max_length=200,
                    ),
                ),
                (
                    "company_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("business_type", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(
                        help_text="Country of operation/residence", max_length=100
                    ),
                ),
                ("address", models.TextField(help_text="Full registered address")),
                ("contact_phone", models.CharField(max_length=30)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "purpose",
                    models.TextField(
                        help_text="Intended use of export-controlled products"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Why you need access to export-controlled items"
                    ),
                ),
                (
                    "product_categories",
                    models.TextField(
                        blank=True,
                        help_text="Specific product categories or types needed",
                    ),
                ),
                (
                    "end_use_statement",
                    models.TextField(
                        blank=True, help_text="Statement of end-use for the products"
                    ),
                ),
                (
                    "supporting_document_1",
                    models.FileField(
                        blank=True,
                        help_text="Business registration, ID, or other proof",
                        null=True,
                        upload_to="licenses/documents/",
                    ),
                ),
                (
                    "supporting_document_2",
                    models.FileField(
                        blank=True, null=True, upload_to="licenses/documents/"
                    ),
                ),
                (
                    "supporting_document_3",
                    models.FileField(
                        blank=True, null=True, upload_to="licenses/documents/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("additional_info_required", "Additional Info Required"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from reviewer"
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "additional_info_request",
                    models.TextField(
                        blank=True, help_text="Details of additional info required"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "max_purchase_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum total value of purchases allowed",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "remaining_purchase_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Remaining purchase value",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "allowed_product_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific product IDs this license covers (empty = all)",
                    ),
                ),
                (
                    "restricted_countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Countries where products cannot be shipped",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "export license",
                "verbose_name_plural": "export licenses",
                "db_table": "verification_export_license",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="verificatio_user_id_8d5cc3_idx"
                    ),
                    models.Index(
                        fields=["status", "-submitted_at"],
                        name="verificatio_status_4bc062_idx",
                    ),
                    models.Index(
                        fields=["license_number"], name="verificatio_license_4541dd_idx"
                    ),
                    models.Index(
                        fields=["valid_until"], name="verificatio_valid_u_1ffdaa_idx"
                    ),
                ],
            },
        ),
    ]
