# Generated by Django 4.2.7 on 2025-12-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0006_exportlicense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportlicense",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual Export License"),
                    ("commercial", "Commercial Export License"),
                    ("government", "Government Export License"),
                    ("defense_contractor", "Defense Contractor License"),
                    ("research", "Research & Development License"),
                    ("reseller", "Authorized Reseller License"),
                    ("companion_18plus", "Companion Robot License (18+)"),
                ],
                max_length=30,
            ),
        ),
    ]
