"""
Django settings for ares_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-*q!vrjz-dt0t$_q4$canojcj-z!qtcio!20+xdnze8of=g*z08",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Local apps
    "users.apps.UsersConfig",
    "products.apps.ProductsConfig",
    "orders.apps.OrdersConfig",
    "support.apps.SupportConfig",
    "analytics.apps.AnalyticsConfig",
    "verification.apps.VerificationConfig",
]

# Custom User Model
AUTH_USER_MODEL = 'users.CustomUser'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # ARES Security Middleware
    "verification.middleware.SecurityAuditMiddleware",
    "verification.middleware.ClearanceRequiredMiddleware",
    # "verification.middleware.IPWhitelistMiddleware",  # Uncomment if IP whitelisting needed
]

# Clearance Protection Configuration
# Note: /orders/purchase-requests/ removed - the view handles robot-specific access checks
CLEARANCE_PROTECTED_PATHS = {
    '/verification/military-robots/': 'military',
    '/verification/review/': 'secret',  # Staff review requires secret clearance
    '/analytics/system-health/': 'secret',
}

# Optional: IP Whitelist for extra security (leave empty to disable)
CLEARANCE_IP_WHITELIST = []  # Example: ['192.168.1.0/24', '10.0.0.0/8']
CLEARANCE_IP_WHITELIST_PATHS = []  # Paths that require IP whitelist

ROOT_URLCONF = "ares_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.notifications",  # Add unread notification count
                "verification.admin_context.admin_notifications",  # Admin pending counts
            ],
        },
    },
]

WSGI_APPLICATION = "ares_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Karachi"  # Pakistan Standard Time (UTC+5)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (User uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication Settings
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email Configuration (Development - Console Backend)
# In development, emails are printed to the console instead of being sent
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@ares.com'

# For production, use SMTP (uncomment and configure):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-password'

# Cache Configuration (for email verification codes)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# WebAuthn/FIDO2 Configuration
WEBAUTHN_RP_ID = 'localhost'  # Change to your domain in production
WEBAUTHN_RP_NAME = 'ARES Marketplace'
WEBAUTHN_ORIGIN = 'http://localhost:8000'  # Change to your domain in production

# =============================================================================
# PRODUCTION SECURITY SETTINGS
# =============================================================================
# Uncomment these settings when deploying to production (HTTPS required)

# Session Security (enable in production with HTTPS)
# SESSION_COOKIE_SECURE = True        # Only send cookies over HTTPS
# SESSION_COOKIE_HTTPONLY = True      # Prevent JavaScript access to session cookie
# SESSION_COOKIE_SAMESITE = 'Lax'     # CSRF protection
# SESSION_COOKIE_AGE = 1209600        # 2 weeks in seconds

# CSRF Security (enable in production with HTTPS)
# CSRF_COOKIE_SECURE = True           # Only send CSRF cookie over HTTPS
# CSRF_COOKIE_HTTPONLY = True         # Prevent JavaScript access

# HTTPS Security Headers (enable in production)
# SECURE_SSL_REDIRECT = True          # Redirect all HTTP to HTTPS
# SECURE_HSTS_SECONDS = 31536000      # 1 year HSTS
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# For production behind a proxy (Nginx, Cloudflare, etc.)
# USE_X_FORWARDED_HOST = True
# USE_X_FORWARDED_PORT = True

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'purchase_request': {
            'format': '[{asctime}] {levelname} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'purchase_request_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'purchase_requests.log',
            'formatter': 'purchase_request',
        },
        'general_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'ares.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'purchase_requests': {
            'handlers': ['console', 'purchase_request_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'orders': {
            'handlers': ['console', 'general_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
