# Generated by Django 4.2.7 on 2025-12-19 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaserequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "purchase request",
                "verbose_name_plural": "purchase requests",
            },
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes or requirements"
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_requests",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="purchaserequest",
            table="orders_purchase_request",
        ),
    ]
