# Generated by Django 4.2.7 on 2025-12-21 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0004_alter_purchaserequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="company_name",
            field=models.CharField(
                blank=True, help_text="Company or organization name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email (if different from account)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="contact_name",
            field=models.CharField(
                blank=True, help_text="Primary contact person", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="intended_use",
            field=models.TextField(
                blank=True, help_text="Detailed description of intended use"
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("commercial", "Commercial Use"),
                    ("research", "Research & Development"),
                    ("government", "Government/Military"),
                    ("education", "Educational"),
                    ("personal", "Personal Use"),
                    ("other", "Other"),
                ],
                default="commercial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection if rejected"
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="review_notes",
            field=models.TextField(blank=True, help_text="Admin/staff review notes"),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_purchase_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="shipping_address",
            field=models.TextField(blank=True, help_text="Full shipping address"),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="shipping_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="shipping_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="supporting_documents",
            field=models.FileField(
                blank=True, null=True, upload_to="purchase_requests/documents/"
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("low", "Low - Within 30 days"),
                    ("normal", "Normal - Within 14 days"),
                    ("high", "High - Within 7 days"),
                    ("urgent", "Urgent - ASAP"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseRequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Request Created"),
                            ("updated", "Request Updated"),
                            ("submitted", "Request Submitted"),
                            ("under_review", "Marked Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("note_added", "Note Added"),
                            ("document_uploaded", "Document Uploaded"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "orders_purchase_request_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
