# Generated by Django 4.2.7 on 2025-12-25 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_robot_required_license"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0006_alter_invoice_options_invoice_billing_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payout_number", models.CharField(max_length=100, unique=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount being paid out",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "earnings_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of earnings included in this payout",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("check", "Check"),
                            ("cryptocurrency", "Cryptocurrency"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=30,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Payment reference number or transaction ID",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_details",
                    models.TextField(
                        blank=True,
                        help_text="Bank account or payment details (JSON format)",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/staff who processed this payout",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Seller receiving this payout",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "seller payout",
                "verbose_name_plural": "seller payouts",
                "db_table": "orders_seller_payout",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerEarnings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gross_sale_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total sale amount before deductions",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Platform commission deducted",
                        max_digits=12,
                    ),
                ),
                (
                    "net_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount seller receives (gross - commission)",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_paid_out",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this earning has been paid to seller",
                    ),
                ),
                (
                    "earned_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("paid_out_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order that generated this earning",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_earnings",
                        to="orders.order",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payout record if this earning has been paid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="earnings",
                        to="orders.sellerpayout",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product sold",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_earnings",
                        to="products.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Seller who earned this amount",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_earnings",
                        to="orders.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "seller earning",
                "verbose_name_plural": "seller earnings",
                "db_table": "orders_seller_earnings",
                "ordering": ["-earned_date"],
            },
        ),
        migrations.CreateModel(
            name="PlatformRevenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "revenue_type",
                    models.CharField(
                        choices=[
                            ("commission", "Sales Commission"),
                            ("listing_fee", "Listing Fee"),
                            ("premium_feature", "Premium Feature"),
                            ("subscription", "Subscription Fee"),
                            ("other", "Other Revenue"),
                        ],
                        default="commission",
                        max_length=30,
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total sale amount before commission",
                        max_digits=12,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Commission percentage (e.g., 10.00 for 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Platform commission earned",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "revenue_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related order if revenue comes from a sale",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_revenues",
                        to="orders.order",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seller from whose sale this commission was generated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_revenues_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related transaction record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_revenues",
                        to="orders.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "platform revenue",
                "verbose_name_plural": "platform revenues",
                "db_table": "orders_platform_revenue",
                "ordering": ["-revenue_date"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("purchase", "Purchase Payment"),
                            ("refund", "Refund"),
                            ("earnings", "Seller Earnings Added"),
                            ("payout", "Seller Payout Deduction"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (positive for credits, negative for debits)",
                        max_digits=12,
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="User's balance before this transaction",
                        max_digits=12,
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="User's balance after this transaction",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "transaction_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="orders.sellerpayout",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_earning",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="orders.sellerearnings",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose wallet is affected",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet transaction",
                "verbose_name_plural": "wallet transactions",
                "db_table": "orders_wallet_transaction",
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-transaction_date"],
                        name="orders_wall_user_id_fba007_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="orders_wall_transac_056373_idx",
                    ),
                    models.Index(
                        fields=["status"], name="orders_wall_status_46f294_idx"
                    ),
                    models.Index(
                        fields=["order"], name="orders_wall_order_i_1c9ce0_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sellerpayout",
            index=models.Index(
                fields=["seller", "-created_at"], name="orders_sell_seller__650b45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerpayout",
            index=models.Index(fields=["status"], name="orders_sell_status_f2d626_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerpayout",
            index=models.Index(
                fields=["payout_number"], name="orders_sell_payout__f1d70a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerearnings",
            index=models.Index(
                fields=["seller", "-earned_date"], name="orders_sell_seller__ef6022_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerearnings",
            index=models.Index(
                fields=["seller", "status"], name="orders_sell_seller__c52ee4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerearnings",
            index=models.Index(fields=["order"], name="orders_sell_order_i_23832a_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerearnings",
            index=models.Index(
                fields=["is_paid_out"], name="orders_sell_is_paid_12eb73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformrevenue",
            index=models.Index(
                fields=["revenue_type", "-revenue_date"],
                name="orders_plat_revenue_e7d09e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformrevenue",
            index=models.Index(
                fields=["seller", "-revenue_date"],
                name="orders_plat_seller__fcff74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformrevenue",
            index=models.Index(fields=["order"], name="orders_plat_order_i_d14503_idx"),
        ),
    ]
