# Generated by Django 4.2.7 on 2025-12-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_robot_required_license"),
        ("orders", "0007_sellerpayout_sellerearnings_platformrevenue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="license_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.product",
            ),
        ),
    ]
