# Generated by Django 4.2.7 on 2025-12-19 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AISystemDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ai_types",
                    models.JSONField(
                        blank=True, default=list, help_text="List of AI_TYPE choices"
                    ),
                ),
                ("has_autonomous_navigation", models.BooleanField(default=False)),
                ("has_object_recognition", models.BooleanField(default=False)),
                ("has_speech_recognition", models.BooleanField(default=False)),
                ("has_decision_making", models.BooleanField(default=False)),
                ("model_name", models.CharField(blank=True, max_length=200)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                (
                    "model_framework",
                    models.CharField(
                        blank=True,
                        help_text="TensorFlow, PyTorch, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "training_data_size",
                    models.CharField(
                        blank=True, help_text="e.g., '1M images'", max_length=100
                    ),
                ),
                (
                    "inference_speed_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Average inference time", null=True
                    ),
                ),
                (
                    "accuracy_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "precision_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "recall_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("supports_online_learning", models.BooleanField(default=False)),
                ("supports_federated_learning", models.BooleanField(default=False)),
                ("can_retrain", models.BooleanField(default=False)),
                ("edge_inference", models.BooleanField(default=True)),
                ("cloud_inference", models.BooleanField(default=False)),
                ("hybrid_inference", models.BooleanField(default=False)),
                (
                    "has_explainability",
                    models.BooleanField(
                        default=False, help_text="AI explainability features"
                    ),
                ),
                ("bias_mitigation", models.BooleanField(default=False)),
                ("safety_constraints", models.JSONField(blank=True, default=list)),
                ("ai_documentation_url", models.URLField(blank=True)),
                ("research_paper_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI system details",
                "verbose_name_plural": "AI system details",
                "db_table": "products_ai_system_details",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "db_table": "products_category",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PowerSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "battery_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lithium_ion", "Lithium-Ion"),
                            ("lithium_polymer", "Lithium-Polymer"),
                            ("nickel_metal_hydride", "Nickel Metal Hydride"),
                            ("lead_acid", "Lead-Acid"),
                            ("fuel_cell", "Fuel Cell"),
                            ("solar", "Solar"),
                            ("wired", "Wired Power"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "battery_capacity_mah",
                    models.PositiveIntegerField(blank=True, help_text="mAh", null=True),
                ),
                (
                    "battery_voltage_v",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volts",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("battery_cells", models.PositiveIntegerField(blank=True, null=True)),
                ("is_removable", models.BooleanField(default=True)),
                (
                    "operating_time_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Typical operating time", null=True
                    ),
                ),
                (
                    "max_operating_time_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum operating time", null=True
                    ),
                ),
                (
                    "charging_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "charging_method",
                    models.CharField(
                        blank=True, help_text="USB-C, Wireless, etc.", max_length=100
                    ),
                ),
                (
                    "idle_power_w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Watts",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "operating_power_w",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "peak_power_w",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "energy_efficiency_rating",
                    models.CharField(
                        blank=True, help_text="A+, A, B, etc.", max_length=10
                    ),
                ),
                ("has_power_saving_mode", models.BooleanField(default=False)),
                ("has_fast_charging", models.BooleanField(default=False)),
                ("supports_wireless_charging", models.BooleanField(default=False)),
                ("supports_solar_charging", models.BooleanField(default=False)),
                ("backup_battery", models.BooleanField(default=False)),
                ("generator_compatible", models.BooleanField(default=False)),
                (
                    "external_power_input",
                    models.CharField(
                        blank=True,
                        help_text="Voltage/Current requirements",
                        max_length=50,
                    ),
                ),
                ("has_overcharge_protection", models.BooleanField(default=True)),
                ("has_short_circuit_protection", models.BooleanField(default=True)),
                (
                    "certification_ul",
                    models.BooleanField(default=False, help_text="UL certification"),
                ),
                (
                    "certification_ce",
                    models.BooleanField(default=False, help_text="CE certification"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "power system",
                "verbose_name_plural": "power systems",
                "db_table": "products_power_system",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for showing discounts",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("track_inventory", models.BooleanField(default=True)),
                ("allow_backorders", models.BooleanField(default=False)),
                (
                    "shipping_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital Delivery"),
                            ("physical", "Physical Shipping"),
                            ("both", "Digital & Physical"),
                        ],
                        default="digital",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("weight_unit", models.CharField(default="g", max_length=10)),
                ("is_digital", models.BooleanField(default=True)),
                (
                    "digital_file",
                    models.FileField(
                        blank=True, null=True, upload_to="digital_products/"
                    ),
                ),
                ("download_limit", models.PositiveIntegerField(default=5)),
                ("download_expiry_days", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                            ("banned", "Banned"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("visibility", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("order_count", models.PositiveIntegerField(default=0)),
                (
                    "rating_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "products_product",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this product"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0-10 priority level"
                    ),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True, help_text="Reminder to purchase", null=True
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Show in public wishlist"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products_product_favorite",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("3d_model", "3D Model"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/gallery/"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="URL for video content"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="products/gallery/files/"
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("caption", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Size in bytes", null=True
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "product gallery item",
                "verbose_name_plural": "product gallery",
                "db_table": "products_product_gallery",
                "ordering": ["order", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField(blank=True)),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("seller_response", models.TextField(blank=True)),
                ("seller_response_at", models.DateTimeField(blank=True, null=True)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("not_helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products_product_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#bef264", help_text="Hex color code", max_length=7
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of products using this tag"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products_product_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "digital_file",
                    models.FileField(
                        blank=True, null=True, upload_to="digital_products/variants/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products_product_variant",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "robot_type",
                    models.CharField(
                        choices=[
                            ("consumer_drone", "Consumer Drone"),
                            ("commercial_drone", "Commercial Drone"),
                            ("industrial_robot", "Industrial Robot"),
                            ("service_robot", "Service Robot"),
                            ("military_autonomous", "Military Autonomous System"),
                            ("research_platform", "Research Platform"),
                            ("medical_robot", "Medical Robot"),
                            ("agricultural_robot", "Agricultural Robot"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(max_length=200)),
                (
                    "year_manufactured",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dimensions_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "dimensions_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "dimensions_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "max_speed_kmh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_altitude_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_payload_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "operating_temperature_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="°C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "operating_temperature_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="°C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True, default=list, help_text="List of certification IDs"
                    ),
                ),
                (
                    "compliance_standards",
                    models.JSONField(
                        blank=True, default=list, help_text="ISO, CE, FCC, etc."
                    ),
                ),
                (
                    "serial_number_format",
                    models.CharField(
                        blank=True,
                        help_text="Format pattern for serial numbers",
                        max_length=50,
                    ),
                ),
                (
                    "requires_verification",
                    models.BooleanField(
                        default=False, help_text="Requires Trust & Verification"
                    ),
                ),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="Restricted hardware requiring clearance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Link to base product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "robot",
                "verbose_name_plural": "robots",
                "db_table": "products_robot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "restriction_level",
                    models.CharField(
                        choices=[
                            ("none", "No Restrictions"),
                            ("age_restricted", "Age Restricted"),
                            ("license_required", "License Required"),
                            ("clearance_required", "Clearance Required"),
                            ("military_only", "Military Only"),
                            ("export_controlled", "Export Controlled"),
                            ("banned", "Banned"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                (
                    "requires_verification",
                    models.BooleanField(
                        default=False,
                        help_text="Requires Trust & Verification approval",
                    ),
                ),
                ("minimum_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "allowed_countries",
                    models.JSONField(
                        blank=True, default=list, help_text="ISO country codes"
                    ),
                ),
                ("restricted_countries", models.JSONField(blank=True, default=list)),
                ("embargoed_countries", models.JSONField(blank=True, default=list)),
                (
                    "export_control_classification",
                    models.CharField(
                        blank=True, help_text="ITAR, EAR, etc.", max_length=100
                    ),
                ),
                ("requires_export_license", models.BooleanField(default=False)),
                (
                    "dual_use",
                    models.BooleanField(default=False, help_text="Dual-use technology"),
                ),
                ("commercial_use_allowed", models.BooleanField(default=True)),
                ("personal_use_allowed", models.BooleanField(default=True)),
                ("research_use_allowed", models.BooleanField(default=True)),
                ("military_use_allowed", models.BooleanField(default=False)),
                ("fcc_id", models.CharField(blank=True, max_length=100)),
                ("ce_marking", models.BooleanField(default=False)),
                ("fda_approved", models.BooleanField(default=False)),
                (
                    "aviation_authority_approved",
                    models.BooleanField(default=False, help_text="FAA, EASA, etc."),
                ),
                ("requires_insurance", models.BooleanField(default=False)),
                ("requires_registration", models.BooleanField(default=False)),
                ("requires_permit", models.BooleanField(default=False)),
                ("legal_notices", models.TextField(blank=True)),
                ("terms_of_use_url", models.URLField(blank=True)),
                ("restricted_airspace", models.BooleanField(default=False)),
                (
                    "restricted_altitude_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("requires_safety_training", models.BooleanField(default=False)),
                ("last_compliance_check", models.DateTimeField(blank=True, null=True)),
                ("compliance_officer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "robot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_restriction",
                        to="products.robot",
                    ),
                ),
            ],
            options={
                "verbose_name": "usage restriction",
                "verbose_name_plural": "usage restrictions",
                "db_table": "products_usage_restriction",
            },
        ),
        migrations.CreateModel(
            name="RobotSpecification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpu_model", models.CharField(blank=True, max_length=100)),
                ("cpu_cores", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ram_gb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "storage_gb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("gpu_model", models.CharField(blank=True, max_length=100)),
                (
                    "camera_resolution",
                    models.CharField(
                        blank=True, help_text="e.g., '4K', '1080p'", max_length=50
                    ),
                ),
                ("camera_count", models.PositiveIntegerField(default=1)),
                ("lidar_enabled", models.BooleanField(default=False)),
                ("radar_enabled", models.BooleanField(default=False)),
                ("gps_enabled", models.BooleanField(default=True)),
                ("imu_enabled", models.BooleanField(default=True)),
                (
                    "sensor_list",
                    models.JSONField(
                        blank=True, default=list, help_text="List of all sensors"
                    ),
                ),
                (
                    "wifi_standard",
                    models.CharField(
                        blank=True, help_text="WiFi 6, 5G, etc.", max_length=20
                    ),
                ),
                ("bluetooth_version", models.CharField(blank=True, max_length=20)),
                ("cellular_support", models.BooleanField(default=False)),
                ("communication_protocols", models.JSONField(blank=True, default=list)),
                ("motor_count", models.PositiveIntegerField(blank=True, null=True)),
                ("motor_type", models.CharField(blank=True, max_length=100)),
                ("servo_count", models.PositiveIntegerField(blank=True, null=True)),
                ("operating_system", models.CharField(blank=True, max_length=100)),
                ("sdk_available", models.BooleanField(default=False)),
                ("api_documentation_url", models.URLField(blank=True)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                (
                    "additional_specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible field for other specs",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "robot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="products.robot",
                    ),
                ),
            ],
            options={
                "verbose_name": "robot specification",
                "verbose_name_plural": "robot specifications",
                "db_table": "products_robot_specification",
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("listing", "Listing Page"),
                            ("detail", "Detail Page"),
                            ("search", "Search Result"),
                            ("recommendation", "Recommendation"),
                        ],
                        default="detail",
                        max_length=20,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Time spent viewing"
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "products_product_view",
                "ordering": ["-created_at"],
            },
        ),
    ]
