# Generated by Django 4.2.7 on 2025-12-19 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="producttag",
            index=models.Index(fields=["slug"], name="products_pr_slug_9b88ae_idx"),
        ),
        migrations.AddIndex(
            model_name="producttag",
            index=models.Index(
                fields=["is_featured", "usage_count"],
                name="products_pr_is_feat_1429b1_idx",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productgallery",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productfavorite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.producttag"
            ),
        ),
        migrations.AddField(
            model_name="powersystem",
            name="robot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="power_system",
                to="products.robot",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="aisystemdetails",
            name="robot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_system",
                to="products.robot",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerestriction",
            index=models.Index(fields=["robot"], name="products_us_robot_i_db5b00_idx"),
        ),
        migrations.AddIndex(
            model_name="usagerestriction",
            index=models.Index(
                fields=["restriction_level", "requires_verification"],
                name="products_us_restric_e96c54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerestriction",
            index=models.Index(
                fields=["requires_export_license"],
                name="products_us_require_8f0f79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="robotspecification",
            index=models.Index(fields=["robot"], name="products_ro_robot_i_05e3bc_idx"),
        ),
        migrations.AddIndex(
            model_name="robot",
            index=models.Index(
                fields=["robot_type"], name="products_ro_robot_t_8b535a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="robot",
            index=models.Index(
                fields=["manufacturer"], name="products_ro_manufac_b12494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="robot",
            index=models.Index(
                fields=["requires_verification", "is_restricted"],
                name="products_ro_require_f58df2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="robot",
            index=models.Index(
                fields=["product"], name="products_ro_product_3bc1b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["product", "-created_at"], name="products_pr_product_bd16e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["user", "-created_at"], name="products_pr_user_id_0ceaeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["view_type", "-created_at"],
                name="products_pr_view_ty_e9dbec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["session_key", "-created_at"],
                name="products_pr_session_3ed1ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active"], name="products_pr_product_3484e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="products_pr_sku_468d6b_idx"),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "is_approved", "-created_at"],
                name="products_pr_product_d9f0c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["user", "-created_at"], name="products_pr_user_id_7badec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["rating", "-created_at"], name="products_pr_rating_a94fbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productgallery",
            index=models.Index(
                fields=["product", "order"], name="products_pr_product_88cc8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productgallery",
            index=models.Index(
                fields=["is_primary"], name="products_pr_is_prim_23a630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productgallery",
            index=models.Index(
                fields=["media_type"], name="products_pr_media_t_dfb7f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productfavorite",
            index=models.Index(
                fields=["user", "-created_at"], name="products_pr_user_id_6712ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productfavorite",
            index=models.Index(
                fields=["product"], name="products_pr_product_c2f0b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productfavorite",
            index=models.Index(
                fields=["priority"], name="products_pr_priorit_1a8eba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productfavorite",
            unique_together={("user", "product")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "visibility"], name="products_pr_status_b19b52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller"], name="products_pr_seller__1bcc9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="products_pr_created_bce1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "-rating_average"],
                name="products_pr_is_feat_56beee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="powersystem",
            index=models.Index(fields=["robot"], name="products_po_robot_i_f04ef7_idx"),
        ),
        migrations.AddIndex(
            model_name="powersystem",
            index=models.Index(
                fields=["battery_type"], name="products_po_battery_4bf391_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="products_ca_slug_da4386_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active"], name="products_ca_parent__1cafc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_featured", "order"], name="products_ca_is_feat_e2c296_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aisystemdetails",
            index=models.Index(fields=["robot"], name="products_ai_robot_i_918544_idx"),
        ),
        migrations.AddIndex(
            model_name="aisystemdetails",
            index=models.Index(
                fields=["has_autonomous_navigation"],
                name="products_ai_has_aut_905aff_idx",
            ),
        ),
    ]
