# Generated by Django 4.2.7 on 2025-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="classification_tag",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("restricted", "Restricted"),
                    ("classified", "Classified"),
                    ("companion", "Companion"),
                    ("controlled", "Controlled"),
                ],
                default="none",
                help_text="Display classification tag",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="is_companion",
            field=models.BooleanField(
                default=False,
                help_text="Companion/humanoid robot (18+ age verification)",
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="required_clearance_priority",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum clearance priority level required (0=none, 25+=classified)",
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="is_restricted",
            field=models.BooleanField(
                default=False,
                help_text="Restricted hardware requiring clearance (military grade)",
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="robot_type",
            field=models.CharField(
                choices=[
                    ("consumer_drone", "Consumer Drone"),
                    ("commercial_drone", "Commercial Drone"),
                    ("industrial_robot", "Industrial Robot"),
                    ("service_robot", "Service Robot"),
                    ("military_autonomous", "Military Autonomous System"),
                    ("research_platform", "Research Platform"),
                    ("medical_robot", "Medical Robot"),
                    ("agricultural_robot", "Agricultural Robot"),
                    ("companion_humanoid", "Companion Humanoid"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="robot",
            index=models.Index(
                fields=["is_companion", "classification_tag"],
                name="products_ro_is_comp_783689_idx",
            ),
        ),
    ]
