# Generated by Django 4.2.7 on 2025-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_robot_classification_tag_robot_is_companion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="required_license",
            field=models.CharField(
                choices=[
                    ("none", "No License Required"),
                    ("individual", "Individual Export License"),
                    ("commercial", "Commercial Export License"),
                    ("government", "Government Export License"),
                    ("defense_contractor", "Defense Contractor License"),
                    ("research", "Research & Development License"),
                    ("reseller", "Authorized Reseller License"),
                    ("companion_18plus", "Companion Robot License (18+)"),
                ],
                default="none",
                help_text="Type of license required to purchase this robot",
                max_length=30,
            ),
        ),
    ]
